modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="vanillaplus"
version="1.0.0"
displayName="Vanilla Plus"
authors="Vanilla Plus Mod"
description='''
A Minecraft Forge mod that adds various vanilla-style items and features.
Starting with custom armor sets inspired by TaTe's Custom Armors and Elytras CIT resource pack.
'''

[[dependencies.vanillaplus]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH" 