modLoader="javafml"
loaderVersion="[47,)"
license="Custom - Attribution Required"

[[mods]]
modId="morearmor"
version="1.0.0"
displayName="More Armor"
authors="YourName"
description='''
A Minecraft Forge mod that adds various vanilla-style armor sets.
Starting with custom armor sets inspired by TaTe's Custom Armors and Elytras CIT resource pack.

Textures by AverageTaTeMan from TaTe's Custom Armors resource pack.
Mod created by Elijah Farrell.

License: Custom - Attribution Required
See LICENSE file for full terms.
'''

[[dependencies.morearmor]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morearmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH" 